#
# Author: RETAMROVEC
#
error:
  amount_not_exist: '&cLS &a>> &7Write amount of hearts you want to give to another
    player, each two numbers equals one heart!'
  zero_health_ban: '&cLS &a>> &7You has been banned for zero hearts on server.'
  without_perm: '&cLS &a>> &7You didt have enough permissions to do that.'
  player_isnt_registered: '&cLS &a>> &7This player is not registered in configuration.'
  cannot_use_shift: '&cLS &a>> &7Dont use shift while crafting, for preventing bug,
    this feature is disabled.'
  too_much_hearts: '&cLS &a>> &7Because you had more HP than 40, your HP got cut
    to 20 HP.'
  too_big_amount_of_hearts: '&cLS &a>> &7You cant have more hearts than 40.'
  cant_withdraw_to_yourself: '&cLS &a>> &7Cant withdraw hearts to yourself. You must withdraw to any player, but not you.'
  cannot_use_command: '&cLS &a>> &7You cant use this command as console.'
  player-is-alive: '&cLS &a>> &7This player is already live.'
  unknown-error: '&cThere is unexpected error! Please report this to server admins for more!'
  player-is-null: '&cLS &a>> &7This target is offline or null.'
messages:
  beacon_expired: '&cLS &a>> &7Your beacon has expired.'
  changed_amount_of_health: '&cLS &a>> &7Amount of health has been changed.'
  heart_get: '&cLS &a>> &7You get one new heart.'
  config_reloaded: '&cLS &a>> &7Config has been successfully reloaded!'
  update_available_notify: '&cLS &a>> &7New update is available, download new version
    at &a/lifesteal spigotmc&7.'
  #
  # Please read this if you want to know what placeholders you should use and why it is different.
  # https://retamrovec.gitbook.io/fine-lifesteal/lifesteal/migrating-from-v8-placeholders
  #
  hearts_get: '&cLS &a>> &7You get some hearts from &a%player_name%&7 your new amount of hearts is %player_max_health%.'
  hearts_sent: '&cLS &a>> &7You sent some hearts to &%player_name%&7 your new amount of hearts is %player_max_health%.'
  recipe_showed: '&cLS &a>> &7Recipe has been showed.'
  recipe_changed: '&cLS &a>> &7Recipe successfully changed!'
  #
  # messages.help DON'T WORK, IN NEWER VERSIONS THIS MAYBE ALREADY WORK!
  #
  help:
    - '&cLS &a>> &7HELP\n'
    - '&7You can use /ls, /lifesteal or /lfs to use plugin commands.\n'
    - '&7/lifesteal set <online player> <amount of hearts> &a(Set specific amount of hearts to player)\n'
    - '&7/lifesteal reload &a(Reload config.yml)\n'
    - '&7/lifesteal author &a(Shows who is author)\n'
    - '&7/lifeSteal spigotMC &a(Sends where plugin can be downloaded)\n'
    - '&7/lifeSteal send &a(You can send some of your hearts to other player)\n'
    - '&7/lifeSteal recipe&c/&7showRecipe &a(Show recipe inGame)\n'
    - '&7/lifeSteal help &a(Send all available commands)'
  player-revived: '&cLS &a>> &7You revived player &c%player_name%&7.'
config:
  #
  # True = yes
  # False = no
  #
  # If you selected true, then you will get always notified, when you join, if new version is on spigotmc.
  # If you selected false, then nothing will happen, and you get notified about new version only in console.
  #
  # WARNING! This option works only for OP or players with lifesteal.admin, if you have "*" permission, it is like OP.
  #
  notify_op_updates: true
  #
  # This option means, if mob will kill you, true = you lose one of your hearts, false = you won't lose anything
  #
  lose_hearts_on_mobs: true
  #
  # Please don't disable this option, this motivates developer to make more and more updates, but if you really want to disable bStats, here you can!
  #
  bStats: true
  #
  # Don't remove beacons because when new revive beacon will be placed, it will be saved there!
  #
  eliminate:
    commands:
      - 'ban %player_name%'
      - 'say %player_name% is just eliminated.'
  revive:
    commands:
      - 'say %player_name% was just revived.'
beacons:
  example: "1, 1, 1"
hologram:
  #
  # Hologram in revive beacon
  #
  1: "&b&lRevive Beacon"
  2: "&7You must wait &c%lifesteal_revive_count% &7seconds"
  3: "&7for revive! You can be revived until &c%lifesteal_beacon_timer%"
recipe:
  #
  # This section is for people, who need own recipe.
  # If you're changing this, there is list of materials.
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  # If you need number where is what item, here is link 
  # https://imgur.com/a/PHN95Zu
  # For nothing in slot, please use "AIR".
  # But use command /lifesteal editRecipe to editRecipe for easier editing.
  #
  ingredients:
    first: GOLD_INGOT
    second: DIAMOND
    third: GOLD_INGOT
    fourth: DIAMOND
    fifth: NETHERITE_INGOT
    sixth: DIAMOND
    seventh: GOLD_INGOT
    eighth: DIAMOND
    ninth: GOLD_INGOT
  #
  # Same as heart recipe.
  #
  revive:
    beacon:
      ingredients:
        first: NETHERITE_INGOT
        second: AIR
        third: NETHERITE_INGOT
        fourth: AIR
        fifth: NETHER_STAR
        sixth: AIR
        seventh: NETHERITE_INGOT
        eighth: AIR
        ninth: NETHERITE_INGOT
developer:
  #
  # This is only option for developer, you can enable it, but you don't need it for features.
  #
  enable: false
player:
  #
  # This section is about how many heart's player have. If you delete config, then data will be deleted with it too.
  # You can change amount of hearts, but don't use 0 or 40 but not 41 and more.
  # Default amount of hearts is 20, that is default amount of hearts for vanilla, and non-modified hearts too.
  #
  example: 20