# ##########################################################################################################
# #												                                                         # #
# #  ##        ##  #######  ##########       ##########  ##########  ##########    ########   ##         # #
# #  ##        ##  ##       ##             ##          	    ##      ##          ##        ##  ##         # #
# #  ##            ##       ##             ##		        ##      ##          ##        ##  ##         # #
# #  ##        ##  #####    ######           ########       ##      ######      ##        ##  ##         # #
# #  ##        ##  ##       ######                   ##     ##      ######      ############  ##	     # #
# #  ##        ##  ##       ##                       ##     ##      ##          ##        ##  ##	     # #
# #  ########  ##  ##       ##                       ##     ##      ##          ##        ##  ##         # #
# #  ########  ##  ##       ##########     ##########       ##      ##########  ##        ##  ########   # #
# #													                                                     # #
# ##########################################################################################################
#
# Author: RETAMROVEC
#
# Translated config.yml
#
plugin:
  version: null
error:
  amount_not_exist: '&cLS &a>> &7Write amount of hearts you want to give to another
    player, each two numbers equals one heart!'
  zero_health_ban: '&cLS &a>> &7You has been banned for zero hearts on server.'
  without_perm: '&cLS &a>> &7You didnt have enough permissions to do that.'
  player_isnt_registered: '&cLS &a>> &7This player is not registered in configuration.'
  cannot_use_shift: '&cLS &a>> &7Dont use shift while crafting, for preventing bug,
    this feature is disabled.'
  too_much_hearts: '&cLS &a>> &7Because you had more HP than 40, your HP got cutted
    to 20 HP.'
  too_big_amount_of_hearts: '&cLS &a>> &7You cant have more hearts than 40.'
  cant_withdraw_to_yourself: '&cLS &a>> &7Cant withdraw hearts to yourself. You must withdraw to any player, but not you.'
  cannot_use_command: '&cLS &a>> &7You can´t use this command as console.'
  player-is-alive: '&cLS &a>> &7This player is already live.'
  unknown-error: '&cThere is unexpected error! Please report this to server admins for more!'
messages:
  changed_amount_of_health: '&cLS &a>> &7Amount of health has been changed.'
  heart_get: '&cLS &a>> &7You get one new heart.'
  config_reloaded: '&cLS &a>> &7Config has been successfuly reloaded!'
  update_available_notify: '&cLS &a>> &7New update is available, download new version
    at &a/lifesteal spigotmc&7.'
  #
  # For both methods, there are available some placeholders.
  # {target} = player, you giving a heart - work for one message (hearts_send
  # {sender} = player, who gived you a heart - work for one message (hearts_get)
  # {amount} = gived amount of hearts - work for both messages (hearts_sent & hearts_get)
  # In both messages you can use {prefix} and {suffix}, so for example, in hearts.get you can get sender's prefix and suffix.
  #
  hearts_get: '&cLS &a>> &7You get &c{amount} &7hearts from &a{sender}&7.'
  hearts_sent: '&cLS &a>> &7You sent &c{amount} &7hearts to &a{target}&7.'
  recipe_showed: '&cLS &a>> &7Recipe has been showed.'
  help:
    - '&cLS &a>> &7HELP\n'
    - '&7You can use /ls, /lifesteal or /lfs to use plugin commands.\n'
    - '&7/lifesteal set <online player> <amount of hearts> &a(Set specific amount of hearts to player)\n'
    - '&7/lifesteal reload &a(Reload config.yml)\n'
    - '&7/lifesteal author &a(Shows who is author)\n'
    - '&7/lifeSteal spigotMC &a(Sends where plugin can be downloaded)\n'
    - '&7/lifeSteal send &a(You can send some of your hearts to other player)\n'
    - '&7/lifeSteal recipe&c/&7showRecipe &a(Show recipe inGame)\n'
    - '&7/lifeSteal help &a(Send all available commands)'
  player-revived: '&cLS &a>> &7You revived player &c{player}&7.'
config:
  #
  # True = yes
  # False = no
  #
  # If you selected true, then you will get always notified, when you join, if new version is on spigotmc.
  # If you selected false, then nothing will happen, and you get notified about new version only in console.
  #
  # WARNING! This option works only for OP or players with lifesteal.admin, if you have "*" permission, it is like OP.
  #
  notify_op_updates: true
  #
  # This option means, if mob will kill you, true = you lose one of your hearts, false = you won't lose anything
  #
  lose_hearts_on_mobs: true
  #
  # Please don't disable this option, this motivates developer to make more and more updates, but if you really want to disable bStats, here you can!
  #
  bStats: true
recipe:
  #
  # This section is for people, who need own recipe.
  # If you doesn't need special recipe, don't change this.
  # If you changing this, there is list of materials.
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  # If you need number where is what item, here is link 
  # https://imgur.com/a/PHN95Zu
  # !! FOR NOTHING IN SLOT, USE MATERIAL "AIR" !!
  # !! ALSO, YOU NEED TO /RELOAD OR RESTART YOUR SERVER TO TAKE CHANGES !!
  #
  ingredients:
    first: GOLD_INGOT
    second: DIAMOND
    thirst: GOLD_INGOT
    fourth: DIAMOND
    fifth: NETHERITE_INGOT
    sixth: DIAMOND
    seventh: GOLD_INGOT
    eighth: DIAMOND
    ninth: GOLD_INGOT
developer:
  #
  # This is only option for developer, you can enable it but you don't need it for features.
  #
  enable: false
player:
  #
  # This section is about how many hearts player have. If you delete config, then data will be deleted with it too.
  # You can change amount of hearts, but don't use 0 or 40 but not 41 and more.
  # Default amount of hearts is 20, that is default amount of hearts for vanilla, and non-modified hearts too.
  #
  example: 20