main: retamrovec.finesoftware.lifesteal.LifeSteal
name: Fine-LifeSteal
version: 1.19-V9.2
api-version: 1.18
author: RETAMROVEC
softdepend: [ PlaceholderAPI ]
commands:
  lifesteal:
    aliases:
    - ls
    - lfs